#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
server:
  tomcat:
    relaxed-query-chars: [ '{','}' ]
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5455/test_database"
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      name: "rtaplatform-kafka-topic"
    consumer:
      auto-offset-reset: earliest
      group-id: "rtaplatform-kafka-consumer"
  data:
    redis:
      host: "127.0.0.1"
      port: 6379